// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr1qIyUJinG73lUSVV-MDiqEMUb4esZbw',
    appId: '1:573369988736:web:aef0e2e5e147f994151865',
    messagingSenderId: '573369988736',
    projectId: 'portfolio-f6071',
    authDomain: 'portfolio-f6071.firebaseapp.com',
    storageBucket: 'portfolio-f6071.firebasestorage.app',
    measurementId: 'G-DK8VY3LH4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7ruWfMYRiWKSeSCKVkiaAk7WC0rFMeec',
    appId: '1:573369988736:android:58dcbc99a4e813ce151865',
    messagingSenderId: '573369988736',
    projectId: 'portfolio-f6071',
    storageBucket: 'portfolio-f6071.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2kpbUmlg_TD3aQZV7d_xtGCcbrXhieoM',
    appId: '1:573369988736:ios:9f21e58fa2f17662151865',
    messagingSenderId: '573369988736',
    projectId: 'portfolio-f6071',
    storageBucket: 'portfolio-f6071.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr1qIyUJinG73lUSVV-MDiqEMUb4esZbw',
    appId: '1:573369988736:web:eb0c1937bfb88a4d151865',
    messagingSenderId: '573369988736',
    projectId: 'portfolio-f6071',
    authDomain: 'portfolio-f6071.firebaseapp.com',
    storageBucket: 'portfolio-f6071.firebasestorage.app',
    measurementId: 'G-F0BQCDH54N',
  );
}
